apiVersion: v1
kind: Service 
metadata:
    name: deploymentservice
spec:
    type: NodePort
    selector:
        app: mynginx
    ports:
    - protocol: TCP
      port: 80
      nodePort: 31018
        

