apiVersion: apps/v1
kind: Deployment
metadata: 
    name: nginx-deployment
    labels:
        app: mynginx
spec:
    replicas: 3
    selector:
        matchLabels:
            app: mynginx
    template:
        metadata:
          labels:
            app: mynginx
        spec:
          containers:
          - name: nginx
            image: pavanmerugu/customnginx
            ports:
            - containerPort: 80


